export const courses = [
  {
    id: "js123abc",
    title: "JavaScript Bootcamp: Beginner to Pro",
    poster: "https://picsum.photos/400/300.webp?random=2",
    outline: [
      "JavaScript Basics",
      "DOM Manipulation",
      "Async Programming",
      "Advanced Patterns",
    ],
    price: 149,
    rating: 4.8,
    platform: "HireScript Learning",
    language: 'English',
    duration: '2 months',
  },
  {
    id: "ux456def",
    title: "UX/UI Design Essentials",
    poster: "https://picsum.photos/400/300.webp?random=3",
    outline: [
      "Design Principles",
      "Wireframing & Prototyping",
      "User Research",
      "Visual Design Systems",
    ],
    price: 179,
    rating: 4,
    platform: "HireScript Learning",
  },
  {
    id: "py789ghi",
    title: "Python for Data Science",
    poster: "https://picsum.photos/400/300.webp?random=4",
    outline: [
      "Python Basics",
      "Data Analysis with Pandas",
      "Visualization with Matplotlib",
      "Machine Learning Introduction",
    ],
    price: 199,
    rating: 4.7,
    platform: "HireScript Learning",
  },
  {
    id: "wp101jkl",
    title: "WordPress Development Masterclass",
    poster: "https://picsum.photos/400/300.webp?random=5",
    outline: [
      "WordPress Setup",
      "Theme Development",
      "Plugin Development",
      "Security & Optimization",
    ],
    price: 129,
    rating: 4.6,
    platform: "HireScript Learning",
  },
  {
    id: "rn112mno",
    title: "React Native Mobile App Development",
    poster: "https://picsum.photos/400/300.webp?random=6",
    outline: [
      "React Native Basics",
      "Navigation & State Management",
      "API Integration",
      "Publishing to App Stores",
    ],
    price: 219,
    rating: 4.8,
    platform: "HireScript Learning",
  },
  {
    id: "pm113pqr",
    title: "Project Management Professional Prep",
    poster: "https://picsum.photos/400/300.webp?random=7",
    outline: [
      "Project Management Frameworks",
      "Agile & Scrum",
      "Risk Management",
      "Stakeholder Communication",
    ],
    price: 249,
    rating: 4.9,
    platform: "HireScript Learning",
  },
  {
    id: "ds114stu",
    title: "Data Structures & Algorithms in Java",
    poster: "https://picsum.photos/400/300.webp?random=8",
    outline: [
      "Big O Notation",
      "Sorting & Searching",
      "Trees & Graphs",
      "Dynamic Programming",
    ],
    price: 189,
    rating: 4.8,
    platform: "HireScript Learning",
  },
  {
    id: "ml115vwx",
    title: "Machine Learning with TensorFlow",
    poster: "https://picsum.photos/400/300.webp?random=9",
    outline: [
      "ML Fundamentals",
      "Neural Networks",
      "Model Optimization",
      "Deployment & Monitoring",
    ],
    price: 299,
    rating: 4.9,
    platform: "HireScript Learning",
  },
];
